= Building the stylesheets

Building requires a recent version of Gradle. Continuous integration
is configured with Travis CI.

Running `gradle clean dist` in the top level will do a complete build.
Release artifacts are stored in `build/distributions`. Here are some
useful targets:

* `clean` – tidies things up
* `compileXslt` – makes runnable stylesheets in `build/xslt`.
* `dist` – builds a distribution
* `testReport` – runs the HTML tests and generates a report. Requires DeltaXML :-(
* `test` – runs all the tests
* `test_html` – runs the HTML tests
* `test_print_css` – runs the CSS print tests
* `test_print_fo` – runs the FO print tests

== Setting up Travis

If you want to make Travis builds work for your fork, you need to
setup secure environment variables in your Travis CI config:

* `GH_TOKEN` – the GitHub token that will allow Travis to publish
* `GIT_NAME` – Your name: Jane Doe
* `GIT_EMAIL` – Your email: jane.doe@example.com
* `GIT_PUB_REPO` – Your repo slug: jane/xslt20-stylesheets

